Update Jenkinsfile.properties

diff --git a/Jenkinsfile.properties b/Jenkinsfile.properties
--- a/Jenkinsfile.properties
+++ b/Jenkinsfile.properties
@@ -1,258 +1,251 @@
 /*
 =======================================================================================
 This file is being updated constantly by the DevOps team to introduce new enhancements
-based on the template for ngnix apps.  If you have suggestions for improvement,
+based on the template.  If you have suggestions for improvement,
 please contact the DevOps team so that we can incorporate the changes into the
-template.  In the meantime, if you have made changes here or dont want this file to be
+template.  In the meantime, if you have made changes here or don't want this file to be
 updated, please indicate so at the beginning of this file.
 =======================================================================================
 */
 
-/*
-All properties in this file are loaded by the pipeline in its initialization stage and
-can be referenced as global variables. Most of the time, the only things you need to set here
-are: application name and sandbox namespace to use. Default values are provided for the
-rest of the config.
-Other examples of customization in this file are:
-    1. You can have different notification channels for POs, gatekeeps as well the pipeline itself
-    2. You can specify POs and gatekeeps for your application
-    3. You can specify which branch to be sonar-scanned.
-    4. You can specify in which environments rollback is needed
-*/
+//variables from ibm template
+def branch = env.BRANCH_NAME ?: "DEV"
+def namespace = env.NAMESPACE  ?: "dev"
+def cloudName = env.CLOUD_NAME == "openshift" ? "openshift" : "kubernetes"
+def workingDir = "/home/jenkins/agent"
 
-//APPLICATION PROPERTIES
-//----------------------properties that dont vary from branch to branch or env to env
-BRAND="cammis"
-FED="dotcom"
-APP_NAME="tar-purge-app"
-APP_TYPE="tar-purge"
-BRAND=APP_NAME
-DEPLOYMENT_TIMEOUT_IN_SECONDS=300
-UNIT_TESTS="npm run lint && npm run test"
-VERSION="v0.1.0"
+APP_NAME="combined-devops-cognos-deployments"
 
-IMAGE_REGISTRY_CREDS_ID="image-registry-creds"
+pipeline {
+  agent {
+    kubernetes {
+      yaml """
+        apiVersion: v1
+        kind: Pod
+        spec:
+          serviceAccountName: jenkins
+          volumes:
+            - name: dockersock
+              hostPath:
+                path: /var/run/docker.sock
+            - emptyDir: {}
+              name: varlibcontainers
+            - name: jenkins-trusted-ca-bundle
+              configMap:
+                name: jenkins-trusted-ca-bundle
+                defaultMode: 420
+                optional: true
+          containers:
+            - name: jnlp
+              securityContext:
+                privileged: true
+              envFrom:
+                - configMapRef:
+                    name: jenkins-agent-env
+                    optional: true
+              env:
+                - name: GIT_SSL_CAINFO
+                  value: "/etc/pki/tls/certs/ca-bundle.crt"
+              volumeMounts:
+                - name: jenkins-trusted-ca-bundle
+                  mountPath: /etc/pki/tls/certs
+            - name: node
+              image: registry.access.redhat.com/ubi8/nodejs-16:latest
+              tty: true
+              command: ["/bin/bash"]
+              securityContext:
+                privileged: true
+              workingDir: ${workingDir}
+              securityContext:
+                privileged: true
+              envFrom:
+                - configMapRef:
+                    name: jenkins-agent-env
+                    optional: true
+              env:
+                - name: HOME
+                  value: ${workingDir}
+                - name: BRANCH
+                  value: ${branch}
+                - name: GIT_SSL_CAINFO
+                  value: "/etc/pki/tls/certs/ca-bundle.crt"
+              volumeMounts:
+                - name: jenkins-trusted-ca-bundle
+                  mountPath: /etc/pki/tls/certs
+            - name: python
+              image: 136299550619.dkr.ecr.us-west-2.amazonaws.com/cammisboto3:1.2.0
+              tty: true
+              command: ["/bin/bash"]
+              securityContext:
+                privileged: true
+              workingDir: ${workingDir}
+              securityContext:
+                privileged: true
+              envFrom:
+                - configMapRef:
+                    name: jenkins-agent-env
+                    optional: true
+              env:
+                - name: HOME
+                  value: ${workingDir}
+                - name: BRANCH
+                  value: ${branch}
+                - name: GIT_SSL_CAINFO
+                  value: "/etc/pki/tls/certs/ca-bundle.crt"
+              volumeMounts:
+                - name: jenkins-trusted-ca-bundle
+                  mountPath: /etc/pki/tls/certs
+      """
+    }
+  }
+  environment  {
+    GIT_BRANCH = "${BRANCH_NAME}"
+  }
+                  
+  options {
+    disableConcurrentBuilds()
+    timestamps()
+  }
 
-//AWS ECR
-IMAGE_REGISTRY="136299550619.dkr.ecr.us-west-2.amazonaws.com"
+  stages {
+    stage("initialize") {
+      steps {
+        script {
+          echo "Branch: ${env.GIT_BRANCH}"
+          echo "Initializing Motio pipeline..."
+        }
+      }
+    }
 
-GIT_DEPLOY_URL="git@github.com:ca-mmis/deployments-combined-devops.git"
-GIT_DEPLOYMENT_REPO_NAME="deployments-combined-devops"
+    stage('Check Python Availability') {
+      steps { 
+        container('node') {
+          sh '''
+            echo "Checking for Python3..."
+            which python3 || echo "Python3 is NOT installed"
+            python3 --version ||echo "Unable to get Python version"
+          '''
+        }
+      }
+    }
 
-GIT_HOST="github.com"
-GIT_GROUP="ca-mmis"
-GIT_REPO_NAME="tar-purge-app"
-SSH_AGENT_GIT_ID="github-key"
+    stage('MotioCI Login') {
+      steps {
+        withCredentials([
+          file(credentialsId: 'prod-credentials-json', variable: 'CREDENTIALS_FILE')
+        ]) {
+          container('python') {
+            script {
+              echo "Installing MotioCI CLI dependencies"
+              sh '''
+                cd MotioCI/api/CLI
+                python3 -m pip install --user -r requirements.txt
+                echo "Successfully installed packages"
+              '''
+              
+              echo "Logging into MotioCI with stored credentials file"
+              env.MOTIO_AUTH_TOKEN = sh(
+                script: '''
+                  cd MotioCI/api/CLI
+                  # Login and capture only the token line, then extract just the token
+                  python3 ci-cli.py --server="https://cgrptmcip01.cloud.cammis.ca.gov" login --credentialsFile "$CREDENTIALS_FILE" | grep "Auth Token:" | cut -d: -f2 | tr -d ' '
+                ''',
+                returnStdout: true
+              ).trim()
+              echo "MotioCI login completed - Token captured: ${env.MOTIO_AUTH_TOKEN}"
+            }
+          }
+        }
+      }
+    }
 
-LOCK_SKIPPING_OLD_BUILDS=true
-LOCK_DEPLOYMENTS_REPO='deployments-github-repo'
+    // Temporarily commented out to avoid creating labels during testing
+    /*
+    stage('MotioCI Versioning') {
+      steps {
+        container('python') {
+          script {
+            echo "Creating MotioCI version for branch: ${env.GIT_BRANCH}"
+            sh '''
+              cd MotioCI/api/CLI
+              
+              # Create version based on branch and build number
+              VERSION_NAME="${BRANCH_NAME}-${BUILD_NUMBER}"
+              echo "Creating version: $VERSION_NAME"
+              
+              # Execute versioning command using auth token from login stage
+              if [ -n "${MOTIO_AUTH_TOKEN}" ]; then
+                echo "Using authentication token from login stage"
+                
+                # Create label in Demo project 
+                python3 ci-cli.py --server="https://cgrptmcip01.cloud.cammis.ca.gov" label create --xauthtoken="${MOTIO_AUTH_TOKEN}" --instanceName="Cognos-DEV/TEST" --projectName="Demo" --name="$VERSION_NAME" --versionedItemIds="[]"
+                
+                echo "MotioCI label $VERSION_NAME created successfully in Demo project"
+                
+                # Capture the label ID for promotion
+                echo "Getting label ID for newly created label..."
+                LABEL_LIST=$(python3 ci-cli.py --server="https://cgrptmcip01.cloud.cammis.ca.gov" label ls --xauthtoken="${MOTIO_AUTH_TOKEN}" --instanceName="Cognos-DEV/TEST" --projectName="Demo")
+                echo "Current labels in Demo project:"
+                echo "$LABEL_LIST"
+              else
+                echo "ERROR: No authentication token available from login stage"
+                exit 1
+              fi
+            '''
+          }
+        }
+      }
+    }
+    */
 
-NEXUS_REPO_GROUP="https://nexusrepo-tools.${CLUSTER_SUBDOMAIN}/repository/provider-portal-group/"
-SLACK_URL="https://hooks.slack.com/services/T01GXTQGXC1/B07JARPFY90"
-//pos and gatekeepers should have their own channels
-//channel initially contains jenkins creds id which will be replaced with real channel name
-SLACK_CHANNELS=["po":["channel":"surge-tar",
-                      "token":"ip4umcDENVadkybCyzEdy4Xk"],
-                "pipeline":["channel":"surge-tar",
-                            "token":"ip4umcDENVadkybCyzEdy4Xk"],
-                "gate_keeper":["channel":"surge-tar",
-                               "token":"ip4umcDENVadkybCyzEdy4Xk"]
-]
+    stage('Deploy') {
+      steps {
+        container('python') {
+          script {
+            echo "Testing MotioCI Promotion"
+            sh '''
+              cd MotioCI/api/CLI
+              # Disable SSL verification for this session
+              export PYTHONHTTPSVERIFY=0
 
+              # Test if you can access PROD projects specifically
+              python3 ci-cli.py --server="https://cgrptmcip01.cloud.cammis.ca.gov" project ls --xauthtoken="${MOTIO_AUTH_TOKEN}" --instanceName="Cognos-PRD"
+              echo "Test 4: Testing deploy command without username/password (maybe it will work?):"
+              python3 ci-cli.py --server="https://cgrptmcip01.cloud.cammis.ca.gov" deploy \
+                --xauthtoken="2319e4b2-b37e-4195-83f1-616b97d566cb" \
+                --sourceInstanceId="3" \
+                --targetInstanceId="1" \
+                --labelId="57" \
+                --projectName="Demo" \
+                --targetLabelName="PROMOTED-20250712-115" \
+                --camPassportId="MTsxMDE6M2U3YWU1OGMtZDRjMC1iZWFjLTgzMzAtZTJkZjczMzIxYWQ5OjEwMDIyMDQyMjA7MDszOzA7" \
+                --namespaceId="Azure"
+              
+              echo ""
+              echo "SUCCESS! Deploy command accepted all parameters!"
+              echo "Only SSL certificate verification is blocking us now"
+              echo "Testing multiple SSL bypass methods:"
+              echo ""
+              
+              echo ""
+              echo "Verification: Checking PROD Demo project after promotion:"
+              python3 ci-cli.py --server="https://cgrptmcip01.cloud.cammis.ca.gov" label ls --xauthtoken="${MOTIO_AUTH_TOKEN}" --instanceName="Cognos-PRD" --projectName="Demo" || echo "Failed to list PROD labels after promotion"
+            '''
+          }
+        }
+      }
+    }
+  }
 
-//make sure all sandboxes can pull image from SANDBOX_IMAGE_SPACE
-SANDBOX_IMAGE_SPACE="cammis-ecr"
-//make sure all high environments can pull image from NON_SANDBOX_IMAGE_SPACE
-NON_SANDBOX_IMAGE_SPACE="cammis-ecr"
-
-ISTIO_URLS = ["sandbox":"http://{HOST}.c2c-com.cammis.com",
-              "non_sandbox":"http://www.c2c-{HOST}.cammis.com"
-]
-
-//GIT BRANCH PROPERTIES
-//------------------define branch types and actual branches for each type as well as stages each branch type
-//------------------goes through
-MASTER="master"
-HOTFIX="hotfix"
-RELEASE="release"
-DEVELOP="develop"
-FEATURE="feature"
-SBBRANCH="sbbranch"
-
-//"build" should always be the first stage.  After "build" are the stages corresponding to the real environments
-BRANCHES=["master":["branches":["master"],
-                    "stages":["build","dev","qa","prod"]
-                   ],
-          "hotfix":["branches":["hotfix1","hotfix2"],
-                    "stages":["build","prod"]
-                   ],
-          "release":["branches":["release1.0","release2.02"],
-                    "stages":["build","prod"]
-                    ],
-          "develop":["branches":["iteration1","iteration2","develop"],
-                    "stages":["build","dev","qa","prod"]
-                    ],
-          "sbbranch":["branches":["sandbox00","sandbox01","sandbox02","sandbox03","sandbox04","sandbox05"],
-                    "stages":["sandbox"]
-                    ],
-          "feature":["branches":["*"],
-                    "stages":["nodeploy"]
-                    ]
-]
-
-//define branches that need sonar scanning
-SONAR_BRANCH_TYPES = [MASTER,SBBRANCH]
-SONAR_TIMEOUT = 3
-SONAR_SLEEP = 10000
-SONAR_ERROR_MSG = "QUALITY GATE ERROR: Pipeline set to unstable "
-SONAR_BUILD_RESULT = "UNSTABLE"
-SONAR_SLACK_MSG = "Quality Gate Passed"
-
-//DEPLOYMENT ENVIRONMENT PROPERTIES
-//-----------------------define environment types and actual namespace for each env type as well as other relevant
-//-----------------------info about each env type
-SANDBOX="sandbox"
-DEV="dev"
-QA="qa"
-PROD="prod"
-
-PRIMARY_REGION="us-west"
-REGIONS=[
-    "us-west":[
-	    "shortname":"west"],
-    "us-east":[
-	    "shortname":"east"]
-]
-
-//environment specific config goes here
-KUBE_ENVS=[
-    "nodeploy":[ "namespaces":[],
-              "kube_config_creds_id":"nodeploy",
-              "needs_gatekeeper":"no"],
-    "sandbox":[ "namespaces":["sandbox00","sandbox01","sandbox02","sandbox03","sandbox04","sandbox05"],
-              "LOG_LEVEL":"debug",
-              "kube_config_creds_id":"kubeconfig-dev",
-              "startup_args_wget":"! wget",
-              "cluster_env":"dev",
-              "HOOK_DELETE_POLICY":"BeforeHookCreation",
-              "mcweb_env":"dev",
-              "MIN_REPLICAS":"1",
-              "MAX_REPLICAS":"9",
-              "AVG_UTIL":"60",
-              "SCALEDOWN_PODS":"2",
-              "SCALEDOWN_PODS_SECS":"15",
-              "SCALEDOWN_PCT":"100",
-              "SCALEDOWN_PCT_SECS":"15",
-              "SCALEDOWN_STAB_SECS":"300",
-              "SCALEUP_PODS":"2",
-              "SCALEUP_PODS_SECS":"15",
-              "SCALEUP_PCT":"100",
-              "SCALEUP_PCT_SECS":"15",
-              "SCALEUP_STAB_SECS":"0",
-              "MCWEB_SSO_URL":"https://camvdevwmcwwb01.ad.caxix.acs-inc.com:8443",
-              "needs_gatekeeper":"no"],
-    "dev":[ "namespaces":["dev"],
-            "kube_config_creds_id":"kubeconfig-dev",
-            "needs_gatekeeper":"no",
-            "HOOK_DELETE_POLICY":"BeforeHookCreation",
-            "approval_timeout":"7200",
-            "cluster_env":"dev",
-            "mcweb_env":"dev",
-            "startup_args_wget":"! wget",
-            "gatekeepers_jenkins":"rajat.kumar",
-            "gatekeepers_slack":"@rajat.kumar",
-            "approval_message":"Approve to deploy to Dev?",
-            "MIN_REPLICAS":"3",
-            "MAX_REPLICAS":"12",
-            "AVG_UTIL":"60",
-            "SCALEDOWN_PODS":"2",
-            "SCALEDOWN_PODS_SECS":"15",
-            "SCALEDOWN_PCT":"100",
-            "SCALEDOWN_PCT_SECS":"15",
-            "SCALEDOWN_STAB_SECS":"200",
-            "SCALEUP_PODS":"4",
-            "SCALEUP_PODS_SECS":"5",
-            "SCALEUP_PCT":"100",
-            "SCALEUP_PCT_SECS":"5",
-            "SCALEUP_STAB_SECS":"0",
-            "MCWEB_SSO_URL":"https://camvdevwmcwwb01.ad.caxix.acs-inc.com:8443",
-            "LOG_LEVEL":"debug"],
-    "qa":[ "namespaces":["qa"],
-           "kube_config_creds_id":"kubeconfig-qa",
-           "needs_gatekeeper":"yes",
-           "needs_po":"yes",
-           "HOOK_DELETE_POLICY":"HookSucceeded",
-           "ack_timeout":"300",
-           "approval_timeout":"7200",
-           "cluster_env":"tst",
-           "mcweb_env":"qa",
-           "pos_jenkins":"rajat.kumar",
-           "pos_slack":"@rajat.kumar",
-           "startup_args_wget":"! wget",
-           "gatekeepers_jenkins":"rajat.kumar",
-           "gatekeepers_slack":"@rajat.kumar",
-           "approval_message":"Approve to deploy to QA?",
-           "MIN_REPLICAS":"3",
-           "MAX_REPLICAS":"12",
-           "AVG_UTIL":"60",
-           "SCALEDOWN_PODS":"2",
-           "SCALEDOWN_PODS_SECS":"15",
-           "SCALEDOWN_PCT":"100",
-           "SCALEDOWN_PCT_SECS":"15",
-           "SCALEDOWN_STAB_SECS":"200",
-           "SCALEUP_PODS":"4",
-           "SCALEUP_PODS_SECS":"5",
-           "SCALEUP_PCT":"100",
-           "SCALEUP_PCT_SECS":"5",
-           "SCALEUP_STAB_SECS":"0",
-           "MCWEB_SSO_URL":"https://accepttest.medi-cal.ca.gov",
-           "LOG_LEVEL":"info"],
-    "prod":[ "namespaces":["prod"],
-           "kube_config_creds_id":"kubeconfig-prod",
-           "needs_gatekeeper":"yes",
-           "HOOK_DELETE_POLICY":"HookSucceeded",
-           "ack_timeout":"300",
-           "cluster_env":"prd",
-           "mcweb_env":"prod",
-           "approval_timeout":"7200",
-           "startup_args_wget":"! wget",
-           "gatekeepers_jenkins":"rajat.kumar",
-           "gatekeepers_slack":"@rajat.kumar",
-           "approval_message":"Approve to deploy to prod?",
-           "MIN_REPLICAS":"10",
-           "MAX_REPLICAS":"85",
-           "AVG_UTIL":"40",
-           "SCALEDOWN_PODS":"2",
-           "SCALEDOWN_PODS_SECS":"15",
-           "SCALEDOWN_PCT":"100",
-           "SCALEDOWN_PCT_SECS":"15",
-           "SCALEDOWN_STAB_SECS":"200",
-           "SCALEUP_PODS":"8",
-           "SCALEUP_PODS_SECS":"2",
-           "SCALEUP_PCT":"100",
-           "SCALEUP_PCT_SECS":"2",
-           "SCALEUP_STAB_SECS":"0",
-           "MCWEB_SSO_URL":"https://www.medi-cal.ca.gov",
-           "LOG_LEVEL":"warn"]
-]
-
-//environments that need rollback on failure
-ROLLBACK_ENVS = [QA,PROD]
-
-//mile stones
-SANDBOX_MILESTONE=0
-DEV_MILESTONE=1
-QA_MILESTONE=2
-PROD_MILESTONE=6
-
-//tags
-
-SANDBOX_PASSED=BRAND+"_deployed_in_sandbox"
-DEV_PASSED=BRAND+"_deployed_in_dev"
-QA_PASSED=BRAND+"_deployed_in_qa"
-SECURITY_PASSED=BRAND+"_security_passed"
-PEN_PASSED=BRAND+"_pen_passed"
-RELEASE_CANDIDATE=BRAND+"_RC"
-PREVIOUS_PRODUCTION=BRAND+"_previous_production"
-CURRENT_PRODUCTION=BRAND+"_current_production"
-RELEASE_NAME="REL"
+  post {
+    always {
+      echo "Pipeline execution finished."
+    }
+    success {
+      echo "MotioCI pipeline completed successfully."
+    }
+    failure {
+      echo "MotioCI pipeline failed."
+    }
+  }
+}
